# Copyright (c) 2026 Hansheng Chen

import contextlib
import os
import time

from concurrent.futures import ThreadPoolExecutor

import torch

from ..builder import MODULES
from .gaussian_flow_mmd import GaussianFlowMMD


@MODULES.register_module()
class GaussianFlowOnPolicy(GaussianFlowMMD):
    """Fully-online on-policy training in the DAGGER band -- no replay buffer.

    The DAGGER arms visit the high-sigma band through a *replay buffer*: a rollout
    round every ``round_interval`` iterations fills ``model.dagger_buffer`` with
    expert-labelled states, and the next few hundred iterations resample it. The
    states therefore go stale between rounds (the policy that generated them is
    several hundred updates old) and every round pays for the expert's image banks.

    Here no STATE is stored. Each iteration rolls the CURRENT policy out from noise
    on the eval sampler/NFE grid, stops at the band edge, and trains at exactly the
    states that rollout visited -- so every point is on-policy for the weights being
    updated, and no rollout state is ever reused after the weights move.

    Two terms are available at those on-policy states, both optional:

    ``cfg_gap_weight`` (w_cfg) -- the CFG-gap matching loss

        || (v_cond - v_uncond) - (v*_cond - v*_uncond) ||^2

        where ``v`` is the model's velocity and ``v*`` the DATA-derived empirical
        velocity of the ground-truth model. The model's two branches come from one
        batched forward of ``2 * band_batch`` rows (true labels | null). The target
        is the empirical expert's gap at the same state: its class-restricted
        posterior mean gives ``v*_cond`` and its whole-dataset posterior mean gives
        ``v*_uncond``, both mapped through ``expert_target`` into the same
        clamp-weighted velocity space, and detached.

        So the band is not asked to make conditioning irrelevant -- it is asked to
        reproduce the CFG gap the data itself implies. The band is precisely the
        region inference leaves unguided (the eval ``guidance_interval`` upper edge
        is 0.88 <= band edge), which is where the model's gap is otherwise never
        corrected by guidance at sampling time.

        ``cfg_gap_target='zero'`` drops ``v*`` and drives the model's own gap to
        zero instead. That is a DIFFERENT objective (it makes the band
        class-agnostic rather than data-matched) and needs the expert for nothing,
        so it is available only as an explicit ablation.

    ``emp_fm_weight`` -- the empirical flow-matching loss at the same states,
        regressing each branch onto its OWN expert velocity (``v_cond -> v*_cond``,
        ``v_uncond -> v*_uncond``). This is DAGGER's ``loss_dagger`` target, taken at
        on-policy states instead of buffered ones, and it shares the gap term's model
        forward and expert evaluation -- so with both on, the second term is free
        apart from the loss arithmetic.

        It is complementary to the gap, not redundant with it. With
        a = v_cond - v*_cond and b = v_uncond - v*_uncond, the gap is ``||a - b||^2``
        while this is ``~ ||a||^2 + ||b||^2``: the gap constrains only the DIFFERENCE
        and is blind to error common to both branches, while this pins the absolute
        level of each. Together they fix both.

    ``mmd_weight`` -- the inherited per-step MMD between the rollout marginal and
        the noised on-path marginal (see :class:`GaussianFlowMMD`). Off by default
        (``mmd_weight=0``).

    Gradient structure, which differs between the two on purpose:

      * the CFG-gap term is a per-point regression at *fixed* visited states, so the
        states are DETACHED before it runs -- the gradient goes into the two
        velocity predictions, never into the trajectory that produced the state.
        That is DAGGER's semantics (visit on-policy, regress pointwise) and it keeps
        the term's gradient independent of the rollout's.
      * MMD is a property of the rollout DISTRIBUTION, so it has no gradient at all
        unless the samples themselves depend on theta: it uses the graph-carrying
        states and backprops through every Heun step in the band.

    Consequently the rollout is built under ``no_grad`` when MMD is off (the common
    case: the CFG-gap term alone needs no trajectory graph), and with the graph only
    when ``mmd_weight != 0``. Turning MMD on is what makes the band expensive.

    The expert is still needed -- it supplies ``v*`` -- but only its banks, built
    fresh each iteration the band runs and never cached across weight updates. What
    is gone is the replay BUFFER of rollout states: the ``DaggerRolloutHook`` must
    not be used and a ``buffer_batch`` is rejected, since states generated by an
    older policy are the thing this class exists to remove. Bank construction is the
    arm's dominant cost -- see :meth:`_build_gap_banks`.

    Args:
        cfg_gap_weight (float): coefficient on the mean-over-band gap-matching loss.
            0 disables the term. The mean is over elements and band steps, with no
            logit-normal reweighting -- the band is a narrow sigma range, so the
            per-sigma weight would be near-constant across it anyway, and a plain
            mean keeps the knob's scale readable against the logged value.
        cfg_gap_max_states (int | None): evaluate the point terms (gap and fm, which
            share a forward) at this many band states
            per iteration, drawn uniformly at random from the band (``None`` = all of
            them). This is the term's MEMORY knob: every scored state holds its own
            ``2 * band_batch``-row forward graph until backward, so all 6 states of a
            0.875 band at ``band_batch=64`` retain ~768 rows of activations -- several
            times the bs=256 flow-matching step. Subsampling is unbiased over
            iterations (the states are drawn uniformly, so each is visited equally
            often in expectation), it only makes the per-iteration estimate noisier.
            The rollout itself still runs the whole band -- it has to, to reach the
            band edge -- so this trades gradient variance for activations, not evals.
        emp_fm_weight (float | str): coefficient on the empirical FM term. 0 disables
            it. ``'mass'`` sets it to ``p_high = P(sigma >= t_split)`` so the band
            carries exactly the sigma mass it does in reg_ft, matching the on-path
            term's ``p_low`` factor -- see the note in __init__.
            Unlike the gap, this one goes through ``self.flow_loss`` (logit-normal
            rescale and the 0.5 factor included), so the logged ``emp_fm`` is directly
            comparable to the DAGGER arms' ``loss_dagger`` -- and is much smaller than
            a raw MSE at these sigmas, where that reweighting down-weights hard.
        cfg_gap_target (str): ``'expert'`` (default) matches the data-derived gap
            ``v*_cond - v*_uncond``; ``'zero'`` is the expert-free ablation that
            drives the model's own gap to zero.
        cfg_gap_detach_uncond (bool): stop-gradient on the MODEL's unconditional
            branch, so the term moves only the conditional field and leaves the
            unconditional one where it is. Default False (both differentiated, so
            the pair meets the target from both sides).
        null_label (int | None): label index for the unconditional branch. ``None``
            -> ``denoising.num_classes`` (the CFG embedding slot, 1000 here), which
            is what the wrapper's ``negative_labels`` carries.
        band_t_split (float | None): band lower edge. ``None`` falls back to
            ``mmd_t_split``, then to ``t_split``.
        band_nfe (int | None), band_batch (int | None), band_sampler (str | None):
            rollout grid / width / scheduler. ``None`` keeps the inherited
            ``mmd_nfe`` / ``mmd_batch`` / ``mmd_sampler``. One band, one rollout:
            both terms read the same states, so these override the MMD names rather
            than sitting beside them.
        band_score_start (bool): also score the point terms (CFG gap, alignment,
            emp_fm) at the t=1 START state of the rollout (pure noise -- inference's
            first eval), not only at the landing states. The gap has a real target
            there: the expert's softmax is flat at t=1, so v*_c - v*_u = x0_u - x0_c,
            the class-mean offset. Start rows are added at the same per-state share as
            each landing state (round(band_rows / n_states)) and drawn from
            trajectories that already get banks, so they cost no image IO. emp_fm's
            logit-normal weight at t=1 is ~1e-52, so its start rows add ~nothing but
            count in its per-row mean. Only MMD leaves the start out -- both of its
            sides are exactly N(0, I) there, so the statistic is identically 0.
            Default False.
        cfg_gap_reweight (bool): weight the CFG gap per row by the flow loss's own
            sigma weight (0.5 * its rescale -- the pretraining logit-normal mass),
            exactly as emp_fm and the on-path FM are, instead of a plain mean. Under
            the logit-normal(0.8, 0.8) weight the rows at 0.98 / t=1 then carry ~0.015
            / ~0. The unweighted value is still logged as cfg_gap_raw. Default False.
    """

    def __init__(self,
                 *args,
                 cfg_gap_weight=1.0,
                 cfg_gap_target='expert',
                 emp_fm_weight=1.0,
                 cfg_gap_max_states=None,
                 cfg_gap_detach_uncond=False,
                 null_label=None,
                 cfg_align_weight=0.0,
                 band_prob_class=0.9,
                 cfg_complement_mode=None,
                 emp_fm_complement_mode=None,
                 band_null_from_batch=False,
                 band_frac_on_path=0.5,
                 allow_no_band_term=False,
                 onpath_truncate='auto',
                 onpath_truncate_rescale=True,
                 band_t_split=None,
                 band_nfe=None,
                 band_batch=None,
                 band_rows='auto',
                 band_class_sampling='uniform',
                 band_classes_per_batch=None,
                 band_sampler=None,
                 band_score_start=False,
                 cfg_gap_reweight=False,
                 **kwargs):
        kwargs.setdefault('mmd_weight', 0.0)   # MMD is opt-IN here, unlike GaussianFlowMMD
        super().__init__(*args, **kwargs)
        self.cfg_gap_weight = float(cfg_gap_weight)
        assert cfg_gap_target in ('expert', 'zero')
        self.cfg_gap_target = cfg_gap_target
        # 'mass' is resolved below, once the band edge is known.
        self.emp_fm_weight = emp_fm_weight if emp_fm_weight == 'mass' \
            else float(emp_fm_weight)
        self.cfg_gap_max_states = None if cfg_gap_max_states is None \
            else int(cfg_gap_max_states)
        self.cfg_gap_detach_uncond = cfg_gap_detach_uncond
        self.null_label = int(null_label) if null_label is not None \
            else int(self.denoising.num_classes)
        # one band shared by every on-policy term -- these overwrite the inherited
        # mmd_* fields so the inherited _band_rollout / _ckpt_pred need no changes.
        if band_t_split is not None:
            self.mmd_t_split = band_t_split
        if band_nfe is not None:
            self.mmd_nfe = int(band_nfe)
        # 'auto' derives the trajectory count from the band's point budget at runtime
        # (see _band_traj_count) instead of pinning it; an int pins it as before.
        # band_rows: how many (trajectory, band-time) PAIRS the point terms score.
        # Decoupled from band_batch (how many trajectories are rolled out) exactly as
        # d-flow decouples n_band_roll from n_roll: rows are free, trajectories cost a
        # bank each, so lowering band_batch alone cuts IO without shrinking the band's
        # share of the objective.
        self.band_rows = band_rows
        self.band_batch_auto = isinstance(band_batch, str) and band_batch == 'auto'
        if band_batch is not None and not self.band_batch_auto:
            self.mmd_batch = int(band_batch)
        if band_sampler is not None:
            self.mmd_sampler = band_sampler
        self.band_score_start = bool(band_score_start)
        self.cfg_gap_reweight = bool(cfg_gap_reweight)
        # On-path FM must STOP at the band edge whenever an on-policy term already
        # supervises the band: emp_fm regresses both branches onto the expert's v*
        # there, so leaving the FM loss full-range supervises the same sigmas twice --
        # once against the true residual noise - x_0 and once against v* -- and the
        # arm's sigma mass stops matching reg_ft. 'auto' truncates exactly when
        # emp_fm is on (True/False force it), mirroring the DAGGER arms' t_split
        # carve; the inherited _sample_t_below_split reads self.t_split, so the band
        # edge is copied there.
        # ALIGNMENT term -- an alternative to the full gap. Writing
        # a = v_cond - v*_cond, b = v_uncond - v*_uncond, this adds
        #     - cfg_align_weight * mean_rows <a/||a||, b/||b||>
        # i.e. it rewards the two branches' residuals POINTING the same way while
        # saying nothing about their size. The gap ||a - b||^2 = ||a||^2 + ||b||^2 -
        # 2<a,b> couples direction and magnitude together; the cosine isolates the
        # direction half, is scale free, and is bounded in [-w, w] -- so unlike a raw
        # <a,b> reward it cannot be gamed by making both branches enormously wrong in
        # the same direction. Magnitudes stay pinned by emp_fm and the on-path FM
        # loss. Use INSTEAD of cfg_gap_weight (set that to 0), or alongside it.
        self.cfg_align_weight = float(cfg_align_weight)
        # CFG dropout for the band's empirical-FM term: each on-policy point is
        # regressed onto ONE branch's expert velocity -- the conditional one with
        # probability band_prob_class, the unconditional one otherwise. This mirrors
        # the DAGGER arms' convention (DaggerRolloutHook's label_time_dropout, at
        # train_cfg.prob_class), so emp_fm here is the same quantity as their
        # loss_dagger rather than a both-branches average. The CFG-gap term is
        # unaffected: it needs v_cond AND v_uncond at every point to form a
        # difference, and a dropped row would compare the unconditional branch
        # against itself and contribute an exact zero.
        assert 0.0 <= band_prob_class <= 1.0
        self.band_prob_class = float(band_prob_class)
        # Fraction of the BAND's sigma mass supervised by REAL data (on-path FM with
        # the true velocity) rather than by the expert at on-policy states -- DAGGER's
        # frac_on_path, which the buffer-free arms previously could not apply because
        # it is consumed in the wrapper's buffer carve. Without it the band has no
        # ground-truth anchor at all and v* (a smoothed bank average) owns the region
        # outright, which is a plausible driver of the mode narrowing those runs showed.
        # Both band terms keep BOTH halves of the target -- subspace AND complement --
        # always. What these select is how the COMPLEMENT is computed, independently
        # per term (None -> inherit diffusion.complement_mode):
        #
        #   'full'    : the complement of the plain velocity toward x0_hat,
        #               P_perp((x_t - x0_hat)/sigma_c). The form the network's
        #               complement head natively produces (its ideal output there is
        #               -x0_hat_comp), which is why every arm so far has used it.
        #   'project' : the low-rank prior, -clamp_coef * x0_hat_comp. The subspace
        #               half is IDENTICAL either way (verified to 1.7e-5); only the
        #               complement differs, and the head can only reach this one by
        #               cancelling its own hard-wired x_t_comp term.
        #
        # 'project' on the DAGGER regression target diverged badly once (loss_dagger
        # stuck at 0.73, FID 4.32 -> 294.6), but that was the full-batch expert loss;
        # for the CFG gap the substituted term largely cancels in the difference
        # (the two branches share the same form, leaving -cc*P_perp(Delta)), so the
        # two modes differ there by a factor of sigma on the complement alone.
        self.cfg_complement_mode = cfg_complement_mode
        self.emp_fm_complement_mode = emp_fm_complement_mode
        # Draw the null bank from the batch's own classes rather than the whole
        # dataset. See EmpiricalExpert.build_banks for why this is off by default;
        # it exists so the choice can be measured against the standard arms.
        self.band_null_from_batch = bool(band_null_from_batch)
        self._bank_pool = None      # single orchestrator thread issuing the bank IO
        self._bank_pending = None   # in-flight bank draw for THIS iteration
        self._bank_ready = None     # (plan, future) prefetched for the NEXT band
        self._band_t = {}           # this band's timings / bank costs, see _log_bank_cost
        self._n_states_key = None   # cache for _n_band_states
        self._n_states = None
        # How the rollout's classes are drawn. 'batch' reuses the minibatch's labels
        # (what this arm did before); 'uniform'/'prior' draw them INDEPENDENTLY of the
        # batch, which is what the buffered DAGGER hook did and what makes real
        # double-buffering possible: a draw that does not depend on a future batch can
        # be issued a whole band interval ahead instead of one iteration ahead.
        assert band_class_sampling in ('batch', 'uniform', 'prior')
        self.band_class_sampling = band_class_sampling
        # Confine the band's trajectories to this many DISTINCT classes (the CFG-side
        # analogue of mmd_classes_per_batch). Unset -> whatever band_class_sampling
        # draws, which over 1000 classes gives ~1 trajectory per class. Set to e.g. 8
        # so each class carries several trajectories.
        #
        # Pair it with band_null_from_batch=True: the empirical v*_uncond is then an
        # average over images from the SAME restricted class set, so the target gap
        # v*_cond - v*_uncond is the gap of the restricted mixture rather than of the
        # full 1000-class marginal. Leaving the null unrestricted while restricting
        # the conditional side makes the two halves of the target gap refer to
        # different universes.
        self.band_classes_per_batch = band_classes_per_batch
        assert 0.0 <= band_frac_on_path <= 1.0
        self.band_frac_on_path = float(band_frac_on_path)
        # permits the w=0 control: every band weight 0, so the arm reduces to the
        # inherited DAGGER objective while still running through this class's code
        # path (which is the point of the control).
        self.allow_no_band_term = bool(allow_no_band_term)
        assert onpath_truncate in ('auto', True, False)
        self.onpath_truncate = onpath_truncate
        self.onpath_truncate_rescale = bool(onpath_truncate_rescale)
        if self._truncate_onpath():
            assert self.mmd_t_split is not None, (
                'onpath_truncate needs a band edge: set band_t_split (or '
                'mmd_t_split) so the on-path FM knows where to stop.')
            self.t_split = self.mmd_t_split
        if self.emp_fm_weight == 'mass':
            # MASS MATCHING, applied to the BAND term only. Both FM terms already
            # share self.flow_loss, so they sit on the same per-point footing; what
            # differs is how much of the sigma axis each speaks for. The band covers
            # only sigma >= t_split, so it carries p_high = P(sigma >= t_split) --
            # at t_split=0.9, ~0.1. Left at 1.0 the band would contribute ten times
            # its share and would dominate the objective.
            #
            # The on-path term carries the matching p_low = P(sigma < t_split)
            # factor (onpath_truncate_rescale), so the two FM terms together
            # reproduce reg_ft's sigma allocation exactly, with v* substituted as the
            # target inside the band:
            #     p_low * mean_{sigma<t}[w L_onpath] + p_high * mean_band[w L_emp]
            # Same invariant the DAGGER arms get from roll_weight='proportional'
            # (w = n_roll/bs), which makes their combined loss one per-point mean over
            # the whole batch. The CFG-gap / alignment terms are NOT part of this
            # normalisation -- they carry their own weights, unscaled.
            # Estimated from the model's OWN timestep_sampler, so it stays correct if
            # the sampling distribution is ever changed away from uniform.
            assert self.t_split is not None, (
                "emp_fm_weight='mass' needs a band edge to measure against; set "
                'band_t_split (and leave onpath_truncate on).')
            # the band's mass MINUS the share handed back to real data
            self.emp_fm_weight = self.high_sigma_fraction() * (1.0 - self.band_frac_on_path)
        # NB the expert's presence is NOT checked here: the wrapper attaches the
        # handle (_dagger_expert) after the diffusion is constructed, so the check
        # lives in _build_gap_banks, at first use.
        assert (self.cfg_gap_weight != 0 or self.emp_fm_weight != 0
                or self.mmd_weight != 0 or self.cfg_align_weight != 0
                or self.allow_no_band_term), (
            'GaussianFlowOnPolicy with cfg_gap_weight, emp_fm_weight and mmd_weight '
            'all 0 has no on-policy term at all -- that is plain reg_ft, so use '
            'GaussianFlow (or the regft config) instead of paying for the band '
            'rollout.')

    def _truncate_onpath(self):
        """Whether the on-path FM loss is restricted to sigma < the band edge."""
        if self.onpath_truncate == 'auto':
            return self.emp_fm_weight != 0
        return bool(self.onpath_truncate)

    def _band_due(self, running_status):
        """Per-iteration gate + micro-batch latch for the band, mirroring
        :meth:`GaussianFlowMMD._mmd_due` but keyed on EITHER on-policy term
        term being enabled. The inherited version short-circuits on ``mmd_weight == 0``,
        which is this class's default (MMD is opt-in), so it would switch the whole
        band off whenever only the CFG-gap term is running."""
        if (self.cfg_gap_weight == 0 and self.emp_fm_weight == 0
                and self.mmd_weight == 0):
            return False
        if running_status is None:
            return True
        it = running_status.get('iteration', 0)
        return it >= self.mmd_start_iter and it % self.mmd_interval == 0

    def _band_claim(self, running_status):
        """True at most ONCE per iteration -- the band runs on one micro-batch. Split
        from _band_due so that merely ASKING whether the band is due cannot burn the
        latch (see GaussianFlowMMD._mmd_claim for the bug that split caused)."""
        if not self._band_due(running_status):
            return False
        if running_status is None:
            return True
        it = running_status.get('iteration', 0)
        if self._mmd_done_iter == it:
            return False
        self._mmd_done_iter = it
        return True

    # ---- the on-policy band terms -------------------------------------------

    def _expert_velocities(self, x_s, sigma, labels, banks):
        """The DATA-derived velocities ``(v*_cond, v*_uncond)`` at one visited state.

        Both come from the empirical expert's posterior-mean data estimate at ``x_s``,
        differing only in which bank each row averages over:

          * ``v*_cond``   -- row ``i`` over its CONDITIONAL bank (``bank_size`` draws
            from row ``i``'s true class), i.e. the class-restricted posterior.
          * ``v*_uncond`` -- the same rows over their NULL bank (``null_bank_size``
            draws from the whole dataset), i.e. the unconditional posterior.

        ``x0_hat`` selects per row by label, so passing the true labels takes the
        conditional banks and passing all-null takes the null banks -- two calls over
        the SAME ``build_banks`` output, no second load. ``expert_target`` then maps
        each posterior mean to a velocity in the clamp-weighted space the model's own
        ``u_t_pred`` lives in, so model and expert velocities are comparable.

        These are fixed data-derived targets: they carry no gradient.
        """
        expert = self._dagger_expert
        cond_banks, null_banks = banks
        # sigma arrives as the per-row vector the caller already built: with one band
        # state drawn per trajectory the rows sit at DIFFERENT sigmas, and x0_hat
        # scores each row at its own noise level.
        t0 = self._synced_clock(x_s.device)
        with torch.no_grad():
            x0_cond = expert.x0_hat(
                x_s, sigma, self.feat_fn, labels,
                cond_banks, null_banks, self.null_label)
            t1 = self._synced_clock(x_s.device)
            x0_uncond = expert.x0_hat(
                x_s, sigma, self.feat_fn, torch.full_like(labels, self.null_label),
                cond_banks, null_banks, self.null_label)
        t2 = self._synced_clock(x_s.device)
        bt = self._band_t
        bt['band_t_x0hat_cond'] = bt.get('band_t_x0hat_cond', 0.0) + (t1 - t0)
        bt['band_t_x0hat_null'] = bt.get('band_t_x0hat_null', 0.0) + (t2 - t1)
        # return the POSTERIOR MEANS, not velocities: the two band terms may map them
        # through different complement modes, and expert_target is pure arithmetic
        # (the bank averaging above is the expensive part, done once).
        return x0_cond.detach(), x0_uncond.detach()

    def _loss_row_weights(self, t):
        """The flow loss's per-row weight at timesteps ``t``: what it multiplies a row's
        flat-mean squared error by (its internal 0.5, then rescale_fn). A plain per-row
        MSE times this, averaged over rows, is exactly flow_loss's value."""
        return self.flow_loss.rescale_fn(torch.full_like(t, 0.5), t)

    def _band_point_losses(self, x_s, sigma, labels, banks=None):
        """Both on-policy point terms at ONE visited state, sharing one model forward
        and one expert evaluation. Returns ``(gap, fm)``; ``fm`` is ``None`` when the
        empirical FM term is off.

        The model's two branches come from a single batched forward over ``[x_s; x_s]``
        with ``[labels; null]``, so the pair is evaluated under identical activations
        and costs one forward of ``2m`` rows rather than two of ``m``. Velocities are
        taken in GaussianFlow's clamp-weighted space (``output * clamp_coef``, the
        ``u_t_pred`` the flow loss regresses), which is also what ``expert_target``
        returns.

        gap -- ``|| (v_cond - v_uncond) - (v*_cond - v*_uncond) ||^2``. Depends only on
            the DIFFERENCE of the two branches, so it is blind to any error common to
            both: a model whose velocities are uniformly offset from the data has zero
            gap loss.
        fm  -- the empirical flow-matching loss. Each point is regressed onto ONE
            branch's expert velocity under CFG dropout: ``v_cond -> v*_cond`` with
            probability ``band_prob_class``, else ``v_uncond -> v*_uncond``. That is
            exactly the DAGGER arms' ``loss_dagger`` convention (one label, one
            target per visited state), evaluated at on-policy states.

        The two are complementary rather than redundant: writing a = v_cond - v*_cond
        and b = v_uncond - v*_uncond, gap = ||a - b||^2 while fm ~ ||a||^2 + ||b||^2.
        The gap pins the CFG-relevant difference and tolerates common-mode error; fm
        pins the absolute level. Together they fix both.

        NB the two use DIFFERENT weightings on purpose: gap is a plain mean (its
        scale stays readable against cfg_gap_weight), while fm goes through
        ``self.flow_loss`` -- logit-normal rescale and the 0.5 factor included -- so
        the logged value is directly comparable to the DAGGER arms' loss_dagger.
        That reweighting is a strong down-weight at these sigmas, so expect fm to log
        much smaller than a raw MSE would.
        """
        m = x_s.size(0)
        # sigma may be a scalar (one state for the whole batch) or a per-ROW tensor
        # (one uniformly-drawn band state per trajectory -- the default sampling).
        sig_vec = sigma.to(x_s).reshape(m) if torch.is_tensor(sigma) \
            else x_s.new_full((m, ), float(sigma))
        t = sig_vec * self.num_timesteps
        both = torch.cat([x_s, x_s], dim=0)
        cond_null = torch.cat(
            [labels, torch.full_like(labels, self.null_label)], dim=0)
        out = self.pred(both, torch.cat([t, t], dim=0), class_labels=cond_null)
        _, _, clamp_coef = self.get_clamp_coef(t=t, x_t=x_s)
        v_cond, v_uncond = out.chunk(2, dim=0)
        v_cond = v_cond * clamp_coef
        v_uncond = v_uncond * clamp_coef

        vs_cond = vs_uncond = vs_fm_c = vs_fm_u = None
        if banks is not None:
            x0_c, x0_u = self._expert_velocities(x_s, sig_vec, labels, banks)
            # the CFG gap and emp_fm each get their own complement treatment
            vs_cond = self.expert_target(x_s, sig_vec, x0_c, mode=self.cfg_complement_mode)
            vs_uncond = self.expert_target(x_s, sig_vec, x0_u, mode=self.cfg_complement_mode)
            vs_fm_c = self.expert_target(x_s, sig_vec, x0_c, mode=self.emp_fm_complement_mode)
            vs_fm_u = self.expert_target(x_s, sig_vec, x0_u, mode=self.emp_fm_complement_mode)

        gap = fm = None
        self_sq = cross = cos = None
        if self.cfg_gap_weight != 0 or self.cfg_align_weight != 0:
            # the detach knob applies to the GAP only: the fm term must keep the
            # gradient on both branches, or it would never train the unconditional
            # field toward its own expert target.
            a = v_cond
            b = v_uncond.detach() if self.cfg_gap_detach_uncond else v_uncond
            if vs_cond is not None:              # 'zero' target leaves v* out (a=v_cond)
                a = a - vs_cond
                b = b - vs_uncond
            # The full CFG term, taken directly:
            #   || (v_cond - v_uncond) - (v*_cond - v*_uncond) ||^2  ==  || a - b ||^2
            # scaled by cfg_gap_weight (w_cfg) where it is added to the loss.
            # cfg_gap_reweight: the flow loss's own per-row sigma weight (0.5 * its
            # rescale, i.e. the pretraining logit-normal mass), so the gap is weighted
            # along sigma exactly as emp_fm and the on-path FM are. None -> plain mean.
            rw = self._loss_row_weights(t) if self.cfg_gap_reweight else None
            wmean = (lambda rows: (rw * rows).mean()) if rw is not None else \
                (lambda rows: rows.mean())
            if self.cfg_gap_weight != 0:
                if rw is not None:
                    gap = wmean((a - b).pow(2).flatten(1).mean(1))
                else:
                    gap = (a - b).pow(2).mean()
                # Diagnostic split of the gap across AsymJiT's rank-8 basis. The loss
                # is over all 196608 dims, of which the subspace is 1.04%, so it is
                # numerically complement-dominated -- but that is only a problem if
                # the complement's share is noise rather than signal. Synthetic
                # modelling says signal and bank-sampling noise follow the SAME
                # spectrum (the error of a bank average IS the data covariance / n),
                # leaving SNR roughly flat across the split; these two scalars test
                # that on real data. gap == cfg_gap_sub + cfg_gap_comp exactly, the
                # projection being orthogonal.
                with torch.no_grad():
                    g = a - b
                    g_sub = self.project_fn(g)
                    # diagnostics carry the same row weighting as the loss, so
                    # cfg_gap == cfg_gap_sub + cfg_gap_comp still holds
                    gap_sub = wmean(g_sub.pow(2).flatten(1).mean(1))
                    gap_comp = wmean((g - g_sub).pow(2).flatten(1).mean(1))
                    # per-row gap (weighted likewise, so gap == gap_rows.mean()), for
                    # logging the t=1 rows apart from the landing ones
                    gap_rows = g.pow(2).flatten(1).mean(1)
                    gap_raw = gap_rows.mean()                # unweighted, comparable to old runs
                    if rw is not None:
                        gap_rows = rw * gap_rows
            # grad-carrying cosine: the alignment term's loss is -w * cos, so
            # minimising it maximises the direction agreement.
            af, bf = a.flatten(1), b.flatten(1)
            cos = ((af * bf).sum(-1)
                   / af.norm(dim=-1).clamp_min(1e-6)
                   / bf.norm(dim=-1).clamp_min(1e-6)).mean()
            # Diagnostics only -- these no longer enter the loss. They report the
            # expansion ||a - b||^2 = ||a||^2 + ||b||^2 - 2<a, b>, so cfg_self and
            # cfg_cross say how much of the term is per-branch magnitude versus
            # residual correlation, and cfg_cos gives the direction agreement with
            # the magnitudes divided out.
            with torch.no_grad():
                self_sq = a.pow(2).mean() + b.pow(2).mean()
                cross = (af * bf).sum(-1).mean() / af.shape[1]   # raw <a,b>, per element
        fm_cond_frac = emp_subfrac = None
        if self.emp_fm_weight != 0:
            # per-row CFG dropout: keep -> regress the CONDITIONAL branch onto
            # v*_cond, else the UNCONDITIONAL branch onto v*_uncond. One branch per
            # point, so this is DAGGER's loss_dagger taken on-policy, not an average
            # over both branches.
            keep = torch.rand(m, device=v_cond.device) < self.band_prob_class
            sel = keep.reshape(m, *([1] * (v_cond.dim() - 1)))
            fm = self.flow_loss(dict(
                u_t_pred=torch.where(sel, v_cond, v_uncond),
                u_t=torch.where(sel, vs_fm_c, vs_fm_u),
                timesteps=t))
            with torch.no_grad():   # where emp_fm's residual sits, as for the gap
                r = torch.where(sel, v_cond, v_uncond) - torch.where(sel, vs_fm_c, vs_fm_u)
                r_sub = self.project_fn(r)
                emp_subfrac = r_sub.pow(2).mean() / r.pow(2).mean().clamp_min(1e-12)
            fm_cond_frac = keep.float().mean().detach()
            emp_subfrac = emp_subfrac.detach()
        # self_sq / cross / cos are returned for LOGGING ONLY (see above).
        return gap, fm, (fm_cond_frac, emp_subfrac), \
            (gap_sub, gap_comp, gap_rows, gap_raw) if gap is not None else None, \
            (None if self_sq is None else self_sq.detach()), \
            (None if cross is None else cross.detach()), cos

    def _band_traj_count(self, x_0, t_split):
        """How many rollout trajectories the band needs, with ``band_batch='auto'``.

        The band should supply the same number of points the DAGGER carve gives the
        high-sigma region: ``p_high * batch``, where ``p_high = P(sigma >= t_split)``
        under the model's own timestep distribution. Each trajectory contributes one
        point per SCORED band state, so

            n_traj = round(p_high * batch)

        and each trajectory contributes exactly ONE band state (drawn uniformly), so
        the band supplies p_high * batch rows -- the same count the DAGGER carve gives
        sigma >= t_split, with the same t-marginal. At t_split=0.92, batch=256 that is
        round(0.080 * 256) = 20.

        Scoring EVERY state of a trajectory instead would multiply the band's share of
        the objective by n_states, which is a change of objective rather than of
        estimator -- so the count is not divided by n_states.
        """
        if not self.band_batch_auto:
            return min(self.mmd_batch, x_0.size(0))
        n = int(round(self.high_sigma_fraction() * x_0.size(0)))
        return max(1, min(n, x_0.size(0)))

    def _draw_band_labels(self, n, device, batch_labels=None):
        """The rollout's classes. Independent of the minibatch unless
        ``band_class_sampling='batch'``; 'prior' follows the dataset's class counts
        (the DAGGER hook's 'proportional'), 'uniform' is flat over the classes."""
        if self.band_class_sampling == 'batch':
            assert batch_labels is not None
            return batch_labels[:n]
        expert = self._dagger_expert
        if self.band_class_sampling == 'prior' and expert is not None \
                and hasattr(expert, 'sample_labels'):
            lab = expert.sample_labels(n, device)
        else:
            lab = torch.randint(0, int(self.denoising.num_classes), (n, ), device=device)
        return self._restrict_classes(lab, device)

    def _restrict_classes(self, lab, device):
        """Collapse a label draw onto ``band_classes_per_batch`` DISTINCT classes.

        The distinct set is taken from the draw itself rather than resampled flat, so
        which classes appear still follows ``band_class_sampling`` ('prior' keeps the
        dataset's class frequencies); only how MANY distinct ones survive changes.
        The surviving classes are then tiled over the rows, giving ~n/C trajectories
        each instead of ~1.
        """
        if self.band_classes_per_batch is None:
            return lab
        n = lab.numel()
        c = max(1, min(int(self.band_classes_per_batch), n))
        uniq = torch.unique(lab)
        if uniq.numel() > c:
            uniq = uniq[torch.randperm(uniq.numel(), device=device)[:c]]
        return uniq[torch.arange(n, device=device) % uniq.numel()]

    def _band_row_count(self, n_batch):
        """How many (trajectory, band-time) pairs the point terms score.

        ``n_batch`` is the FULL micro-batch, not the trajectory slice: this is the
        band's share of the training batch, so reading it off an already-sliced x_0
        would shrink it to p_high * p_high * batch.

        ``'auto'`` is the band's own point budget, ``round(p_high * batch)`` -- the
        same count the DAGGER carve gives sigma >= t_split, so the band keeps its
        share of the objective whatever the trajectory count is.
        """
        if self.band_rows == 'auto':
            return max(1, int(round(self.high_sigma_fraction() * n_batch)))
        return max(1, int(self.band_rows))

    def _n_band_states(self, x_ref, t_split):
        """How many states :meth:`_band_rollout` returns, read off the solver grid
        WITHOUT rolling out (same loop as there), so the scored (trajectory, band time)
        pairs can be drawn before the rollout. Checked against the rollout at use."""
        seq_len = x_ref.shape[2:].numel()
        key = (seq_len, float(t_split), self.mmd_nfe, self.mmd_t_hi, self.mmd_sampler)
        if self._n_states_key != key:
            grid = self._build_mmd_sampler(seq_len, x_ref.device).sigmas
            n_pre = 0
            if self.mmd_t_hi is not None:
                while 2 * (n_pre + 1) < len(grid) \
                        and float(grid[2 * (n_pre + 1)]) > self.mmd_t_hi:
                    n_pre += 1
            n_band = n_pre
            while 2 * (n_band + 1) < len(grid) \
                    and float(grid[2 * (n_band + 1)]) >= t_split:
                n_band += 1
            self._n_states_key, self._n_states = key, n_band - n_pre
        return self._n_states

    def _needs_banks(self):
        """Whether any enabled term reads v*: the fm term always does, the gap and
        alignment terms unless running the expert-free 'zero' ablation."""
        return self.emp_fm_weight != 0 or (
            (self.cfg_gap_weight != 0 or self.cfg_align_weight != 0)
            and self.cfg_gap_target == 'expert')

    def _draw_band_plan(self, x_0, t_split, batch_labels=None):
        """Everything random about one band BEFORE it runs: the rollout's classes and
        the scored (trajectory, band time) pairs, drawn independently as in d-flow.

        Drawing the pairs up front is what lets the bank IO skip trajectories no row
        will score: ``n_rows`` draws with replacement over ``m`` trajectories hit only
        ~``m * (1 - (1 - 1/m)^n_rows)`` distinct ones (~13.5 of 21 at the defaults),
        and banks are loaded for exactly those (``traj``). The draw is the same as
        before -- only its timing moves -- so the estimator is unchanged.
        """
        m = self._band_traj_count(x_0, t_split)
        labels = self._draw_band_labels(m, x_0.device, batch_labels)
        n_rows = self._band_row_count(x_0.size(0))
        n_states = self._n_band_states(x_0, t_split)
        j_pick = torch.randint(m, (n_rows, )).tolist()
        k_pick = torch.randint(n_states, (n_rows, )).tolist()
        plan = dict(labels=labels, j_pick=j_pick, k_pick=k_pick,
                    n_states=n_states, traj=sorted(set(j_pick)))
        if self.band_score_start:
            # t=1 rows for the point terms, at the share each landing state gets. Drawn
            # from the trajectories already holding banks, so they add no IO; the
            # trajectories are i.i.d., so this is still a uniform draw over them.
            n_start = max(1, int(round(n_rows / max(n_states, 1))))
            traj = plan['traj']
            plan['j_start'] = [traj[i] for i in torch.randint(len(traj), (n_start, )).tolist()]
        return plan

    def _prefetch_banks(self, plan):
        """Issue the bank IO BEFORE the flow-matching step, mirroring the MMD target
        prefetch. Only the trajectories in ``plan['traj']`` -- the ones some scored
        row actually reads -- get banks.

        Bank construction is 85% image loading (measured: 3.51s of 4.13s per
        trajectory), and none of it depends on anything the rollout produces -- only
        on the labels, known here. Issuing it now gives the reads the whole FM
        forward/backward plus the rollout to finish in, so the cost leaves the step
        time instead of merely shrinking.

        Only the IO runs on the thread: paths are drawn and decoded to uint8 CPU
        tensors, and the encode/feat_fn half stays on the main thread at consumption,
        so no CUDA call is ever made off-thread. The null draw stays INDEPENDENT per
        trajectory -- this changes when the loading happens, not what is loaded.
        """
        expert = self._dagger_expert
        if expert is None or not expert.ready or not self._needs_banks():
            return
        if self._bank_pool is None:
            self._bank_pool = ThreadPoolExecutor(max_workers=1)
        labels = plan['labels']
        # the null restriction still follows the rollout's FULL class set, not just
        # the scored trajectories', so band_null_from_batch means what it did before
        drawn = expert.draw_bank_paths(
            self._plan_bank_labels(plan),
            null_classes=labels.tolist() if self.band_null_from_batch else None)
        self._bank_pending = self._bank_pool.submit(
            self._timed_load, expert, drawn, time.perf_counter())

    @staticmethod
    def _timed_load(expert, drawn, t_issue):
        """``expert.load_bank_images`` stamped with when the draw was issued and how
        long the load itself took, so consumption can tell whether the IO is hidden
        (``band_t_load`` < ``band_t_window``) and by how much. Pure host code: safe on
        the prefetch thread."""
        t0 = time.perf_counter()
        loaded = expert.load_bank_images(drawn)
        loaded['t_issue'] = t_issue
        loaded['t_load'] = time.perf_counter() - t0
        return loaded

    @staticmethod
    def _synced_clock(device):
        """``perf_counter`` once the device's queued work has finished, so the span
        between two calls is the GPU time it covers rather than its launch time."""
        if device.type == 'cuda':
            torch.cuda.synchronize(device)
        return time.perf_counter()

    @staticmethod
    def _plan_bank_labels(plan):
        """Labels of the trajectories that get banks, in ``plan['traj']`` order."""
        labels = plan['labels']
        return labels[torch.as_tensor(plan['traj'], device=labels.device)]

    def _drop_bank_pending(self):
        """Discard an unconsumed bank draw (claimed iteration that then bailed out)."""
        if self._bank_pending is not None:
            self._bank_pending.cancel()
            self._bank_pending = None

    def _build_gap_banks(self, plan, encode_fn, device):
        """One :meth:`EmpiricalExpert.build_banks` call per iteration, shared by every
        scored state (the banks depend on the row's class, not on sigma). Returns
        banks for ``plan['traj']`` only, in that order.

        This is the expensive part of the arm: ``band_batch * (bank_size +
        null_bank_size)`` images are loaded and encoded, every iteration the band
        runs. Budget it with ``band_batch``, the expert's ``bank_size`` /
        ``null_bank_size``, and ``mmd_interval`` -- see the config's cost note.
        """
        expert = self._dagger_expert
        assert expert is not None and expert.ready, (
            'the empirical expert is required whenever a term reads v* -- the '
            'empirical FM term always does, and the CFG-gap term does unless it is '
            "running cfg_gap_target='zero'. v* is an average over per-class image "
            'banks, so set model.expert in the config (the wrapper hands the '
            "diffusion its handle). For a fully expert-free arm set emp_fm_weight=0 "
            "AND cfg_gap_target='zero'.")
        assert encode_fn is not None, (
            'the expert needs an encode_fn (images -> diffusion input space) to build '
            'its banks; the wrapper supplies it as expert_encode_fn. Got None.')
        t_consume = time.perf_counter()
        if self._bank_pending is not None:
            loaded = self._bank_pending.result()      # in flight since forward_train
            self._bank_pending = None
        else:                                         # fallback: synchronous, IO inline
            labels = plan['labels']
            drawn = expert.draw_bank_paths(
                self._plan_bank_labels(plan),
                null_classes=labels.tolist() if self.band_null_from_batch else None)
            loaded = self._timed_load(expert, drawn, t_consume)
        t_ready = time.perf_counter()
        banks = expert.finish_banks(loaded, encode_fn, self.feat_fn, device)
        self._log_bank_cost(loaded, banks, t_consume, t_ready,
                            self._synced_clock(device), device)
        return banks

    def _log_bank_cost(self, loaded, banks, t_consume, t_ready, t_done, device):
        """What this band's expert banks cost, and the largest NULL bank (images per
        trajectory) each resource would allow at the current settings -- logged so
        the ceiling on null_bank_size is read off a run instead of guessed.

        Timings (s): ``band_t_wait`` the main thread blocked on the IO (~0 when the
        prefetch hides it), ``band_t_load`` the IO itself on the prefetch thread,
        ``band_t_window`` how long the IO had between issue and use, ``band_t_finish``
        the GPU half (upload + feats). Memory (GiB, this rank): ``band_mem_gpu_bank``
        the resident bank feats, ``band_mem_host_bank`` the banks' host copies,
        ``band_mem_gpu_free`` device total minus the PEAK reserved so far,
        ``band_mem_host_avail`` the node's MemAvailable.

        Estimates (null images per trajectory, everything else held fixed), each
        linear in what one more null image costs:
          * ``null_bank_max_gpu``    -- the GPU headroom over its resident feats (both
            orientations, every null bank) plus x0_hat's two transient [M, Df]
            temporaries for one row. Conservative: it assumes the banks coexist with
            the all-time peak, which they may not.
          * ``null_bank_max_host``   -- the node's available RAM over its host copy,
            twice (the bank in use and the next band's in flight) on every local rank.
          * ``null_bank_max_hidden`` -- the largest bank whose load still fits the
            prefetch window, taking load time proportional to images loaded. Above it
            the IO stops being free and ``band_t_wait`` turns positive.
        """
        from .experts.empirical_expert import U8Bank
        bt = self._band_t
        bt['band_t_wait'] = t_ready - t_consume
        bt['band_t_load'] = loaded['t_load']
        bt['band_t_window'] = t_consume - loaded['t_issue']
        bt['band_t_finish'] = t_done - t_ready

        def distinct(bank_list):     # aliased (deduped / shared) banks are held once
            return list({id(b): b for b in bank_list}.values())

        def feats(b):
            return b.feats if isinstance(b, U8Bank) else b[1]

        def host_bytes(b):
            return b.u8.nbytes if isinstance(b, U8Bank) else b[0].nbytes

        gib = float(2 ** 30)
        cond_b, null_b = distinct(banks[0]), distinct(banks[1])
        bt['band_mem_gpu_bank'] = sum(feats(b).nbytes for b in cond_b + null_b) / gib
        bt['band_mem_host_bank'] = sum(host_bytes(b) for b in cond_b + null_b) / gib
        if device.type == 'cuda':
            gpu_free = (torch.cuda.get_device_properties(device).total_memory
                        - torch.cuda.max_memory_reserved(device))
        else:
            gpu_free = 0
        host_avail = 0
        try:
            with open('/proc/meminfo') as f:
                for line in f:
                    if line.startswith('MemAvailable:'):
                        host_avail = int(line.split()[1]) * 1024
                        break
        except OSError:
            pass
        bt['band_mem_gpu_free'] = gpu_free / gib
        bt['band_mem_host_avail'] = host_avail / gib

        null_u8 = loaded['null_u8']
        n_null = null_u8[0].shape[0] if null_u8 else 0   # images per null bank
        bt['band_null_imgs'] = float(n_null)
        if not null_b or n_null == 0:
            return
        # per extra null image (one more per bank, in every distinct null bank)
        f0 = feats(null_b[0])
        per_entry = f0[0].nbytes                          # one entry's feats, bytes
        n_orient = f0.shape[0] // n_null
        gpu_per_img = len(null_b) * n_orient * per_entry + 2 * n_orient * per_entry
        host_per_img = (len(null_u8) * null_u8[0][0].nbytes * 2
                        * int(os.environ.get('LOCAL_WORLD_SIZE', 1)))
        bt['null_bank_max_gpu'] = n_null + gpu_free / gpu_per_img
        bt['null_bank_max_host'] = n_null + host_avail / host_per_img
        n_cond_imgs = sum(u.shape[0] for u in loaded['cond_u8'])
        n_null_imgs = sum(u.shape[0] for u in null_u8)
        if loaded['t_load'] > 0:
            per_img_load = loaded['t_load'] / max(n_cond_imgs + n_null_imgs, 1)
            fits = bt['band_t_window'] / per_img_load      # images loadable in the window
            bt['null_bank_max_hidden'] = max(fits - n_cond_imgs, 0.0) / len(null_u8)

    def _onpolicy_loss(self, x_0, plan, t_split, encode_fn=None):
        """One shared band rollout; the CFG-gap and (optional) MMD terms on top.
        ``plan`` (from :meth:`_draw_band_plan`) fixes the classes and scored pairs."""
        self._band_t = {}
        t_band = self._synced_clock(x_0.device)
        labels = plan['labels']
        m = labels.numel()
        x_0 = x_0[:m].detach()

        use_mmd = self.mmd_weight != 0
        use_fm = self.emp_fm_weight != 0
        use_gap = self.cfg_gap_weight != 0
        use_align = self.cfg_align_weight != 0
        use_point = use_gap or use_fm or use_align  # terms sharing the per-state forward
        # The trajectory graph exists only for MMD: the CFG-gap term reads detached
        # states, so with MMD off the rollout is pure inference and costs no
        # activations. See the class docstring.
        ctx = contextlib.nullcontext() if use_mmd else torch.no_grad()
        # band_score_start: the point terms also score the t=1 start state. It is split
        # off here, so `states` stays the landing states the plan and MMD index.
        with_start = self.band_score_start and use_point and plan.get('j_start')
        with ctx:
            states = self._band_rollout(x_0, labels, t_split, include_start=bool(with_start))
        start = None
        if with_start:
            start, states = states[0], states[1:]

        # ONE band state per trajectory, drawn uniformly -- so the band contributes
        # exactly m rows with the band's own t-marginal, and the point terms are an
        # estimator of the band's objective rather than n_states copies of it. MMD is
        # unaffected below: it is a set statistic and still uses every state.
        pick = None
        if use_point and states:
            # INDEPENDENT draws over (trajectory, band time), matching d-flow: a
            # trajectory may supply several rows or none. Rows and trajectories are
            # separate knobs -- the band's t-marginal stays uniform over the grid
            # either way, but the row count no longer has to equal the rollout width.
            # The pairs were drawn in _draw_band_plan, before the rollout, so the
            # banks could be loaded for the scored trajectories alone.
            assert len(states) == plan['n_states'], (
                f"band rollout returned {len(states)} states but the plan was drawn "
                f"over {plan['n_states']}; _n_band_states is out of sync with "
                '_band_rollout.')
            j_pick, k_pick = list(plan['j_pick']), plan['k_pick']
            xs = [states[k][1][j].detach() for j, k in zip(j_pick, k_pick)]
            sigs = [states[k][0] for k in k_pick]
            land_rows = None
            if start is not None:
                # t=1 rows appended after the landing ones (land_rows marks the latter,
                # for logging the two apart); every point term scores all rows
                n_land = len(j_pick)
                xs += [start[1][j].detach() for j in plan['j_start']]
                sigs += [start[0]] * len(plan['j_start'])
                j_pick += plan['j_start']
                land_rows = torch.arange(len(j_pick), device=x_0.device) < n_land
            x_pick = torch.stack(xs)
            sig_pick = x_0.new_tensor(sigs)
            lab_pick = labels[torch.as_tensor(j_pick, device=labels.device)]
            pick = (x_pick, sig_pick, lab_pick, j_pick, land_rows)

        # One bank set per iteration, reused by every scored state, for the scored
        # trajectories only (plan['traj']).
        banks = None
        if self._needs_banks():
            banks = self._build_gap_banks(plan, encode_fn, x_0.device)

        gap_sigmas, gap_vals, fm_vals = [], [], []
        self_vals, cross_vals, cos_vals, frac_vals = [], [], [], []
        sub_vals, comp_vals, empsub_vals, t1_vals, land_vals, raw_vals = [], [], [], [], [], []
        if pick is not None:
            # banks are indexed by position in plan['traj'], so re-index them onto the
            # drawn rows: row i scores against trajectory j_pick[i]'s banks.
            banks_pick = banks
            if banks is not None:
                pos = {j: i for i, j in enumerate(plan['traj'])}
                banks_pick = ([banks[0][pos[j]] for j in pick[3]],
                              [banks[1][pos[j]] for j in pick[3]])
            gap, fm, fmdiag, gsplit, self_sq, cross, cos = self._band_point_losses(
                pick[0], pick[1], pick[2], banks=banks_pick)
            gap_sigmas.append(float(pick[1].mean()))
            if True:
                if gap is not None:
                    gap_vals.append(gap)
                    sub_vals.append(gsplit[0]); comp_vals.append(gsplit[1])
                    raw_vals.append(gsplit[3])
                    if pick[4] is not None:   # the gap at t=1 vs at the landing states
                        t1_vals.append(gsplit[2][~pick[4]].mean())
                        land_vals.append(gsplit[2][pick[4]].mean())
                if fm is not None:
                    fm_vals.append(fm)
                    frac_vals.append(fmdiag[0]); empsub_vals.append(fmdiag[1])
                if self_sq is not None:
                    self_vals.append(self_sq)
                    cross_vals.append(cross)
                if cos is not None:
                    cos_vals.append(cos)

        mmd_loss = mmd_log_vars = None
        if use_mmd:
            # The target is class-matched to the BAND's labels, the ones the rollout
            # was generated under. The micro-batch rows qualify only under
            # band_class_sampling='batch', where the band reuses their labels; the
            # independent 'uniform'/'prior' draws take their targets from disk by
            # label (GaussianFlowMMD._target_per_row).
            mmd_loss, mmd_log_vars = self._mmd_score(
                states, x_0, labels,
                rows_match=self.band_class_sampling == 'batch')

        # *mmd_accum_steps cancels train_grad_accum's 1/N (both terms run on ONE
        # micro-batch, not all N). The extra *world_size applies to the MMD term
        # ALONE: its pooled estimate leaves each rank differentiating only its own
        # rows, so the per-rank gradients SUM to the true gradient and DDP's
        # averaging would shrink it by 1/W. The CFG-gap term is an ordinary
        # per-point mean -- every rank computes the same quantity over its own
        # rows -- so DDP averaging is already correct and it must NOT be rescaled.
        # The empirical-FM term is likewise an ordinary per-point mean.
        acc = float(self.mmd_accum_steps)
        loss = x_0.new_zeros(())
        log_vars = dict(band_steps=loss.new_tensor(float(len(states)) * acc),
                        band_traj=loss.new_tensor(float(m)),
                        band_banks=loss.new_tensor(
                            float(len(plan['traj'])) if banks is not None else 0.0),
                        band_rows=loss.new_tensor(
                            float(pick[0].shape[0]) if pick is not None else 0.0))

        if gap_vals:
            gap = torch.stack(gap_vals).mean()
            loss = loss + self.cfg_gap_weight * gap * acc
            log_vars['cfg_gap'] = gap.detach() * acc
            log_vars['cfg_gap_states'] = loss.new_tensor(float(len(gap_vals)) * acc)
            for sigma, v in zip(gap_sigmas, gap_vals):
                log_vars[f'cfg_gap_s{sigma:.3f}'] = v.detach() * acc
            log_vars['loss_cfg_gap'] = (self.cfg_gap_weight * gap).detach() * acc
            # where the gap's energy sits: subspace is 8/768 = 1.04% of the dims, so
            # cfg_gap_sub >> 0.0104 * cfg_gap means class structure concentrates in
            # AsymJiT's basis and a projected target would be worth testing.
            gs = torch.stack(sub_vals).mean(); gc = torch.stack(comp_vals).mean()
            log_vars['cfg_gap_sub'] = gs * acc
            log_vars['cfg_gap_comp'] = gc * acc
            log_vars['cfg_gap_subfrac'] = gs / (gs + gc).clamp_min(1e-12) * acc
            if self.cfg_gap_reweight:   # the unweighted gap, comparable to plain-mean runs
                log_vars['cfg_gap_raw'] = torch.stack(raw_vals).mean() * acc
            if t1_vals:   # band_score_start: the t=1 rows' share of the gap, kept apart
                log_vars['cfg_gap_t1'] = torch.stack(t1_vals).mean() * acc
                log_vars['cfg_gap_land'] = torch.stack(land_vals).mean() * acc
                log_vars['band_rows_t1'] = loss.new_tensor(float((~pick[4]).sum()) * acc)
        if cos_vals:
            cos_mean = torch.stack(cos_vals).mean()
            if self.cfg_align_weight != 0:
                # loss = -w * cos, so minimising it MAXIMISES the direction
                # agreement between the two branches' residuals. Bounded in [-w, w]
                # and scale free, so magnitudes stay the business of emp_fm.
                loss = loss - self.cfg_align_weight * cos_mean * acc
                log_vars['loss_cfg_align'] = \
                    (-self.cfg_align_weight * cos_mean).detach() * acc
                log_vars['w_align'] = loss.new_tensor(self.cfg_align_weight * acc)
            log_vars['cfg_cos'] = cos_mean.detach() * acc
        if self_vals:
            # the two halves of the gap, logged separately so the sweep is readable:
            # cfg_self = ||a||^2 + ||b||^2, cfg_cross = <a, b> (raw, unweighted).
            log_vars['cfg_self'] = torch.stack(self_vals).mean() * acc
            log_vars['cfg_cross'] = torch.stack(cross_vals).mean() * acc
            log_vars['w_cfg'] = loss.new_tensor(self.cfg_gap_weight * acc)
        if fm_vals:
            fm = torch.stack(fm_vals).mean()
            loss = loss + self.emp_fm_weight * fm * acc
            log_vars['emp_fm'] = fm.detach() * acc
            for sigma, v in zip(gap_sigmas, fm_vals):
                log_vars[f'emp_fm_s{sigma:.3f}'] = v.detach() * acc
            log_vars['loss_emp_fm'] = (self.emp_fm_weight * fm).detach() * acc
            # realised conditional fraction -- should sit at band_prob_class (0.9)
            log_vars['fm_cond_frac'] = torch.stack(frac_vals).mean() * acc
            log_vars['emp_fm_subfrac'] = torch.stack(empsub_vals).mean() * acc
        if mmd_loss is not None:
            # already carries *mmd_accum_steps and the pooled *world_size (see
            # GaussianFlowMMD._mmd_score); its logged values are the true MMD^2
            loss = loss + self.mmd_weight * mmd_loss
            log_vars.update(mmd_log_vars)
            tags = ('mmd_sub', 'mmd_raw') if self.mmd_feature == 'both' else (
                'mmd_sub' if self.mmd_feature == 'subspace' else 'mmd_raw', )
            log_vars['loss_mmd'] = self.mmd_weight * sum(mmd_log_vars[t] for t in tags)
        # the band's forward wall time (its backward runs later, fused with the FM
        # term's) and the bank costs gathered on the way -- see _log_bank_cost
        self._band_t['band_t_total'] = self._synced_clock(x_0.device) - t_band
        for k, v in self._band_t.items():
            log_vars[k] = loss.new_tensor(float(v) * acc)
        return loss, log_vars

    def forward_train(
            self,
            x_0,
            visual_encoder_features=None,
            running_status=None,
            buffer_batch=None,
            n_onpath_high=0,
            class_labels_true=None,
            expert_encode_fn=None,
            **kwargs):
        # the MMD term's disk-drawn targets need the encoder too, and the truncated
        # on-path branch below never reaches GaussianFlowMMD.forward_train to set it
        if expert_encode_fn is not None:
            self._encode_fn = expert_encode_fn
        # A replay buffer is allowed ONLY when it feeds the inherited DAGGER stream
        # while the band terms stay online. The band's own points always come from a
        # rollout taken with the CURRENT weights -- never from the buffer -- so the
        # CFG-gap/alignment/MMD terms remain strictly on-policy even here. What the
        # buffer must not do is supply those band points, which it cannot: it is
        # consumed only by GaussianFlowDagger.forward_train below.
        # Claim + prefetch BEFORE the flow-matching step: the claim decides which
        # micro-batch runs the band, and issuing the bank IO here buys it the whole
        # FM forward/backward plus the rollout to complete in.
        t_split_pre = self.mmd_t_split if self.mmd_t_split is not None else self.t_split
        band_labels = class_labels_true if class_labels_true is not None \
            else kwargs.get('class_labels', None)
        run_band = (self._band_claim(running_status) and t_split_pre is not None
                    and band_labels is not None)
        plan = None
        if run_band:
            if self._bank_ready is not None:
                # DOUBLE BUFFER: this draw was issued when the PREVIOUS band ran, so
                # it has had the whole inter-band interval (mmd_interval iterations)
                # to load rather than a single FM step.
                plan, self._bank_pending = self._bank_ready
                self._bank_ready = None
            else:
                # first band of the run (or after an interval change): no buffer yet
                plan = self._draw_band_plan(x_0, t_split_pre, band_labels)
                self._prefetch_banks(plan)

        assert buffer_batch is None or not self._truncate_onpath(), (
            'a DAGGER buffer and an on-path truncation cannot both be active: the '
            'buffer carve already reserves the high-sigma rows, so truncating on top '
            'would leave the band supervised twice. Set emp_fm_weight=0 to let the '
            'DAGGER stream own the band, or drop the DaggerRolloutHook.')

        # On-path flow matching. Truncated to sigma < the band edge whenever an
        # on-policy term already covers the band (see onpath_truncate), so the two
        # supervisions are exclusive: FM owns sigma < t_split, the band terms own
        # sigma >= t_split. Otherwise full-range, exactly as reg_ft.
        if self._truncate_onpath():
            # band_frac_on_path of the band's mass goes to REAL data: draw that many
            # on-path rows from sigma >= t_split instead of below it, so the on-path
            # term covers sigma < t_split PLUS a mix-in inside the band, exactly as
            # DAGGER's carve does. n_above is the share of this batch that lands in
            # the band, conditional on the row being an on-path row.
            p_high = self.high_sigma_fraction()
            f = self.band_frac_on_path
            w_on = (1.0 - p_high) + p_high * f      # this term's total sigma mass
            n_above = int(round(x_0.size(0) * (p_high * f) / max(w_on, 1e-8)))
            loss, log_vars = self._onpath_loss(
                x_0, truncate=True, use_expert=False, n_above=n_above, **kwargs)
            log_vars['onpath_n_above'] = loss.new_tensor(float(n_above))
            if self.onpath_truncate_rescale:
                # Truncation alone leaves the WHOLE batch below the split, so the
                # data region would carry 1/P(sigma < t_split) ~ 1.14x its reg_ft
                # mass and the effective LR there would jump. Scaling by that
                # probability restores reg_ft's allocation exactly -- what the DAGGER
                # arms get instead by carving the batch into n_on / n_roll rows.
                loss = loss * w_on
                log_vars['onpath_w'] = loss.new_tensor(w_on)
        else:
            # forward the DAGGER buffer through: GaussianFlowDagger.forward_train
            # mixes its expert-labelled rollout term in as the usual convex
            # combination, leaving that objective bit-identical to the plain arm.
            loss, log_vars = super().forward_train(
                x_0,
                visual_encoder_features=visual_encoder_features,
                running_status=running_status,
                buffer_batch=buffer_batch,
                n_onpath_high=n_onpath_high,
                **kwargs)

        t_split = self.mmd_t_split if self.mmd_t_split is not None else self.t_split
        # the CFG-gap term needs the TRUE class labels: kwargs['class_labels'] has
        # already had CFG dropout applied, and a row relabelled to null would compare
        # the unconditional branch against itself and contribute an exact zero. The
        # wrapper supplies the undropped labels; fall back to the dropout-applied
        # ones if it did not (the term then just loses those rows' signal).
        if run_band:
            band_loss, band_log_vars = self._onpolicy_loss(
                x_0, plan, t_split, encode_fn=expert_encode_fn)
            loss = loss + band_loss
            log_vars.update(band_log_vars)
            self._drop_bank_pending()   # this band's draw is spent
            # Queue the NEXT band's banks now. Only possible because the classes are
            # drawn independently of the minibatch: they do not wait on a future
            # batch, so the load gets the entire interval to finish in.
            if self.band_class_sampling != 'batch' and self._dagger_expert is not None:
                nxt = self._draw_band_plan(x_0, t_split)
                self._prefetch_banks(nxt)
                self._bank_ready = (nxt, self._bank_pending)
                self._bank_pending = None
        else:
            self._drop_bank_pending()

        return loss, log_vars
